### ISSUE TITLE
Header navigation menu hover effect

### ISSUE THREAD

**Issue by cnviradiya** [deity-io/falcon#393]
Currently, there are on the full width I'm able to select the menu instead of we make just on the text of the menu title. Because might be this will affect on the more menu items.

**Current Behaviour:**
![Deity_menu_hover_issue](https://user-images.githubusercontent.com/9442993/55624513-d2e56900-57c3-11e9-8c48-b0fee609232b.png)

A clear and concise description.
Here is the my solution:
Menu will not be select in full width.

**After fixed behaviour:**
![Deity_menu_hover_issue_after](https://user-images.githubusercontent.com/9442993/55624710-61f28100-57c4-11e9-92d8-351f992a5e5d.png)

I'm able to make this fix.

**Comment by cane-lagerwaard** [comment]
Hi @cnviradiya! Thanks for your proposal, please note that the screenshots are related to demo.deity.io, this is an altered and extended version of the default theme.

snapshot.deity.io uses the default theme and latest version of Falcon, but the navigation remains the same, I just wanted to point that out :)

Is my assumption correct that you want to make it so multiple columns can be displayed? If so, that was also on our to-do list, please feel free to submit a PR :)

**Comment by cnviradiya** [comment]
Hello @cane-lagerwaard 
Yes, I seen screenshot is given with your demo but I've fix with the default theme.

Thank you :)

**Comment by tutok** [comment]
Hi @cnviradiya 

I would not consider this as an issue in `@deity/falcon-ui` package so [PR](https://github.com/deity-io/falcon/pull/396) is not required.

I think you want to change your shop theme, so you should edit `[path-to-your-shop]/client/src/theme.js` file. Please find `components` property and put your `navbar` theme configuration there, for example:

```
  createTheme({
    components: {
      navbar: {
        display: 'inline-block',
      }  
    }
  }
```

Please let me know if it will work for you.

Bare in mind that in the same way you can override styles for any component from `@deity/falcon-ui` and `@deity/falcon-ecommerce-uikit`

**Comment by cnviradiya** [comment]
Hi @tutok 

You mean to it's functionality?
You can also select menu from at right corner from the navigation menu as I mentioned in the first screenshot.

**Comment by tutok** [comment]
@cnviradiya, yes I mean about `Navbar` behavior. Submenu (with subcategories builded from `NavbarItem`s) is extended to entire available space, so I can not see anything wrong, with the possibility of clicking into individual subcategory `NavbarItem` on its occupied space.

The idea of having `@deity/falcon-ui` package is to provide a set of basic UI building blocks. And as you can imagine it is not possible to cover all styling expectations. So we try to apply as simple as possible, minimal and not obtrusive styling on its components.

Your PR is changing that, I men only "text" is clickable, (which is achieved due to setting `display: block;` on NavbarItem) but the background of submenu stay as it was, so it will confuse the users.

If you would like to have a Navbar menu looked like following 
![image](https://user-images.githubusercontent.com/1831641/55724479-c94e4200-5a0b-11e9-80b1-5d1bd09e4b7e.png)
https://magento.deity.io/women/bottoms-women.html
we could eventually think about adding additional `variant` for `Navbar` menu.

But like I already mentioned, we do not want to block your work so you can easily override "default" look and feel of any `@deity/falcon-ui`s component in your project.

**Comment by cnviradiya** [comment]
@tutok Okay,

Then In you demo where is the magento's submenu?

**Comment by cane-lagerwaard** [comment]
@cnviradiya that's not something we have at the moment, perhaps it's something you'd be interested in to work on? I'd also like to point out that next month we'll start with new designs and start working on a new demo shop. These designs will be made available for the community, so it's easier to contribute

**Comment by Borales** [comment]
Closing this issue. Please feel free to re-open it if you still think some work needs to be done on the Falcon side.
