### ISSUE TITLE
GraphiQL

### ISSUE THREAD

**Issue by DanielRuf** [deity-io/falcon#442]
**Is your feature request related to a problem? Please describe.**
As a developer I would like to want GraphiQL for local testing but I found no info about it in falcon in the docs.

**Describe the solution you'd like**
I would like to have GraphiQL available during development.

**Comment by Piralein** [comment]
If you set the "debug" attribute in the server config true, it should be available at http://localhost:4000/graphql

**Comment by Borales** [comment]
@DanielRuf https://falcon.deity.io/docs/falcon-server/basics#configuration - there's a `debug` flag description. 

it probably needs a better description though :) we will work on it.

**Comment by DanielRuf** [comment]
Well, but https://github.com/prisma/graphql-playground is not GraphiQL, or did I miss something?

**Comment by Borales** [comment]
@DanielRuf true, but since there's GraphQL Playground (thanks to ApolloServer package with a built-in https://github.com/prisma/graphql-playground) - it should be sufficient for testing purposes, I don't see a reason to add another IDE.

If you still want to use GraphiQL - https://github.com/skevy/graphiql-app/releases there's a standalone app for major OSes.

**Comment by DanielRuf** [comment]
@Borales thanks, I'll guess I will go with prisma/graphql-playground then.
