### ISSUE TITLE
Big server.js file in client/build

### ISSUE THREAD

**Issue by DanielRuf** [deity-io/falcon#600]
**What should be changed/improved?**
Currently the client builds a 2MB server.js file in the build directory. For what is it used?

**Your suggested solution**
Remove unused files from client build. It should not contain server files.

**Comment by tutok** [comment]
>Currently the client builds a 2MB server.js file in the build directory. For what is it used?

We need to have a single `server.js` bundle for various reasons:
- because we support module replacement, with HMR at the same time, we can not find any better solution using latest webpack  (documented) API
- falcon-client is used to compile ready to deploy application (not library nor framework) so I can not find any reason why we can not include required `node_modules` into a bundle


> Remove unused files from client build. It should not contain server files.
Can you please elaborate more on this? What do you mean by saying "client build"? Please remember that you create this issue for `server.js` file so which is output of server build. 

Can you please point (as for an example) which files are added into `server.js` bundle while the should not?

**Comment by DanielRuf** [comment]
> Can you please elaborate more on this? What do you mean by saying "client build"? Please remember that you create this issue for `server.js` file which is the output of server build.

This file was created when I did `yarn build` in the client folder.

**Comment by tutok** [comment]
Ok, thanks. So after [npx create-falcon-app my-app](https://falcon.deity.io/docs/getting-started/installation) you get two folders `client` and `server`.
`client` folder contains web server implementation and because we have SSR, `falcon-client build` produces also [`app/client/build/`] `server.js` file.

then can you please answer for an outstanding question?
>Can you please point (as for an example) which files are added into `server.js` bundle while the should not?

**Comment by DanielRuf** [comment]
This is probably an issue with missing treeshaking. See #603 and #605. I will close this here. Thanks for the answers.
