### ISSUE TITLE
Better icon support

### ISSUE THREAD

**Issue by DanielRuf** [deity-io/falcon#605]
**What should be changed/improved?**
Currently all unused icons in theme.js are included in the client and server bundle which is not great for the performance.

**Your suggested solution**
* support for loading icons from relative paths
* compress icons with svgo
*

**Comment by tutok** [comment]
you are right, if some icon is not used, but is referenced via the `theme` it will be included into output bundle. But this is the cost of having a centralized theme, and you need to keep it up to date.

There is one alternative, you can require and render them inline instead of through `theme`, then due to code splitting not used icons will not be bundled.

**Comment by DanielRuf** [comment]
> you are right, if some icon is not used, but is referenced via the `theme` it will be included into output bundle. But this is the cost of having a centralized theme, and you need to keep it up to date.
> 
> There is one alternative, you can require and render them inline instead of through `theme`, then due to code splitting and three shaking not used icons will not be bundled.

This is what we have done and what should be also documented and the recommended way to ship only changes / updates to the needed files and decrease bundle filesizes.

**Comment by tutok** [comment]
I think, if you do not like to use `theme.icons` you can always import image files directly
