### ISSUE TITLE
Improve lint script

### ISSUE THREAD

**Issue by DanielRuf** [deity-io/falcon#629]
**What should be changed/improved?**
A clear and concise description.

**Your suggested solution**
Currently eslint runs on all direcotries using `./` which includes `build`. It should be probably `./src`.

**Comment by tutok** [comment]
adding `.eslintignore` in root directory should help
```
build/
coverage/
*.log
node_modules/
```

please note that this is actually related to https://github.com/deity-io/falcon/issues/628, and right now it makes more sense to remove the following script https://github.com/deity-io/falcon/blob/2e5d478804c60240a8c186b818ad722af6d2bb6b/examples/shop-with-blog/client/package.json#L18 instead of improving it.
