### ISSUE TITLE
Missing .gitignore files

### ISSUE THREAD

**Issue by DanielRuf** [deity-io/falcon#666]
**What should be changed/improved?**
The generated structure does not have any .gitignore file in client and server directory so all node_modules files are tracked by default. This should not be the case.

**Your suggested solution**
Generate .gitignore files.

![grafik](https://user-images.githubusercontent.com/827205/67106931-d07cb680-f1cb-11e9-955d-13650f095230.png)

**Comment by DanielRuf** [comment]
They should contain the cache and node_modules folders.

**Comment by DanielRuf** [comment]
They should contain the `build` and `node_modules` folders.

**Comment by EddyVinck** [comment]
I just did some digging, and [the examples directory is gitignored](https://github.com/deity-io/falcon/blob/dev/packages/create-falcon-app/.gitignore#L3) even though [that directory is used by `create-falcon-app`](https://github.com/deity-io/falcon/blob/dev/packages/create-falcon-app/src/index.js#L9). I'm not sure why, but that prevents adding a gitignore file to the example. I assume the examples folder from the project root is just copied to this location, but I need to look into it further or get some help. @Borales do you know why this is? I'd like to fix this seemingly simple issue but it is a bit more complicated than I expected.

**Comment by Borales** [comment]
@EddyVinck `packages/create-falcon-app/examples` is being gitignored because we copy `examples` folder from the root, so NPM would include it to the `create-falcon-app` package when it is being published to npmjs.org. 

But Daniel refers to an issue with not having `.gitignore` file in `examples/shop-with-blog/client`
 and `examples/shop-with-blog/server` folders (and a reason for having separate `.gitignore` files is because of potentially keeping these 2 apps in separate repositories, thus preserving `.gitignore` file for each "project"). 

So, the issue could be resolved by adding basic `.gitignore` files to the mentioned folder.

**Comment by DanielRuf** [comment]
Right, I meant what @Borales describes.

**Comment by EddyVinck** [comment]
> we copy examples folder from the root
That's good to know. I'll make a PR with the file added to the /examples directory in a bit
